backend:
  name: github
  repo: aqsmallwood/amc360
  branch: main # or master, depending on your default branch

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "about"
    label: "About"
    folder: "src/content/about"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "males"
    label: "Male Dogs"
    folder: "src/content/dogs/males"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Long Alias Heading", name: "longAlias", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Weight (lbs)", name: "weight", widget: "number" }
      - { label: "Head Size (inches)", name: "headSize", widget: "number" }
      - { label: "Height (inches)", name: "height", widget: "number" }
      - { label: "Still Growing", name: "stillGrowing", widget: "boolean", default: false }
      - { label: "Description", name: "body", widget: "markdown" }

  - name: "females"
    label: "Female Dogs"
    folder: "src/content/dogs/females"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Long Alias Heading", name: "longAlias", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Weight (lbs)", name: "weight", widget: "number" }
      - { label: "Head Size (inches)", name: "headSize", widget: "number" }
      - { label: "Height (inches)", name: "height", widget: "number" }
      - { label: "Still Growing", name: "stillGrowing", widget: "boolean", default: false }
      - { label: "Description", name: "body", widget: "markdown" }

  - name: "breedings"
    label: "Breedings"
    folder: "src/content/breedings"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Father", name: "father", widget: "relation", collection: "males", search_fields: ["name"], value_field: "{{slug}}", display_fields: ["name"] }
      - { label: "Mother", name: "mother", widget: "relation", collection: "females", search_fields: ["name"], value_field: "{{slug}}", display_fields: ["name"] }
      - { label: "Father Image", name: "fatherImage", widget: "image" }
      - { label: "Mother Image", name: "motherImage", widget: "image" }
      - { label: "Items", name: "items", widget: "list", fields: [
        { label: "Title", name: "title", widget: "string" },
        { label: "Price", name: "price", widget: "number" },
        { label: "Sold", name: "sold", widget: "boolean", default: false }
      ]}
      - { label: "Description", name: "body", widget: "markdown" }